@startuml
[*] --> AllShows: Application loaded
AllShows --> ShowDetails: Select show
AllShows --> EditShowCrawler: Add new show
AllShows --> ImportShowCrawlerFromJson: Import show crawler from json
EditShowCrawler --> CrawlingInProgress: Save show crawler
EditShowCrawler --> EditCrawler: Configure part crawler
EditCrawler --> CrawlPreview: Preview
CrawlPreview --> CrawlLog: View log
CrawlLog --> CrawlLogEntryDetails: View log entry details
ShowDetails --> CrawlingInProgress: Crawl
ShowDetails --> CrawlLog: View last crawl log
ShowDetails --> Dialog: Clear watch history / Delete show
ShowDetails --> EditShowCrawler: Edit crawler
ShowDetails --> ShowPlayer: Play / Play specified episode
ShowPlayer --> Dialog: Finished watching entire show
@enduml