CREATE TABLE IF NOT EXISTS CRAWL_LOG_ENTRY(
    ID INTEGER PRIMARY KEY,
    SHOW_ID TEXT NOT NULL,
    VALUE TEXT NOT NULL,
    INPUT TEXT,
    OUTPUT TEXT
);

CREATE TABLE IF NOT EXISTS SHOW_CRAWLER(
    SHOW_ID TEXT PRIMARY KEY,
    CRAWLER TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "SHOW"(
    ID TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    THUMBNAIL_URL TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS EPISODE(
    ID INTEGER NOT NULL,
    SHOW_ID TEXT NOT NULL,
    NAME TEXT NOT NULL,
    VIDEO_URL TEXT NOT NULL,
    PRIMARY KEY(ID, SHOW_ID),
    CONSTRAINT FK_SHOW FOREIGN KEY (SHOW_ID) REFERENCES "SHOW"(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS EPISODE_VIEW(
    SHOW_ID TEXT NOT NULL,
    EPISODE_ID TEXT NOT NULL,
    LAST_WATCH_DATE BIGINT NOT NULL,
    PROGRESS REAL NOT NULL,
    PRIMARY KEY(SHOW_ID, EPISODE_ID)
);